server:
  port: 7010

logging:
  file: common-microservice-config.log
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tianjin8gang/config-resource-microservice.git
          searchPaths: /*